engines:
    fixme:
        enabled: true
    phpmd:
        enabled: true
        config:
            rulesets: "codesize,controversial,design,naming,unusedcode"

ratings:
    paths:
        - '**.php'

exclude_paths:
    - 'tests/'
