language: php

sudo: required

php:
    - 7.1
    - 7.0
    - 5.6

before_install:
    - 'sudo add-apt-repository -y ppa:chris-lea/libsodium'
    - 'sudo apt-get -q update'
    - 'sudo apt-get -y install libsodium-dev'
    - 'pecl install libsodium'

install:
    - composer --no-interaction --no-progress install
    - composer show --installed

script: vendor/bin/phpunit
